### ISSUE TITLE
Nimbledroid dashboard not showing WebView test results since August 9

### ISSUE THREAD

**Issue by cpeterso** [mozilla/firefox-health-dashboard#132]
@armenzg - The Firefox Health dashboard for Android Nimbledroid tests doesn't show any WebView (WV) test result since August 9. It still shows recent GeckoView results.

https://health.graphics/android/graph?site=https://mic.com/stories/262/the-art-of-an-organized-refrigerator

@npark-mozilla wonders if this is related to a change in the Focus version numbers where Nimbledroid is reporting version 7.0.1 for both Klar (GeckoView) and Focus (WebView).

**Comment by armenzg** [comment]
I will look at this after my 1x1. If you need me to cancel my meeting let me know (via IRC/Slack) and I will do so.

**Comment by armenzg** [comment]
The API from Nimbledroid is timing out after 120 seconds.
My mechanism to report failures failed.
I noticed that my fetching script only failed once I cleared the Redis db.

I've reported the issue to Nimbledroid. I also made reference to my concerns about the API back on July 17th.

**Comment by armenzg** [comment]
Script failure ==> exit code != 0 ==> fantastic

> armenzg@armenzg-mbp backend$ yarn fetchNimbledroidData
> yarn run v1.9.4
> $ node build/nimbledroid.js
> Fetching each product can take between 20-40 seconds.
> Fetching klar
> https://nimbledroid.com/api/v2/users/npark@mozilla.com/apps/org.mozilla.klar/apks
> Fetching focus
> https://nimbledroid.com/api/v2/users/npark@mozilla.com/apps/org.mozilla.focus/apks
> Response for https://nimbledroid.com/api/v2/users/npark@mozilla.com/apps/org.mozilla.klar/apks not OK: 502
> TypeError: Cannot read property 'map' of null
>     at removeConsoleMessage (/Users/armenzg/repos/health/backend/build/webpack:/src/utils/NimbledroidClient/index.js:12:19)
>     at /Users/armenzg/repos/health/backend/build/webpack:/src/utils/NimbledroidClient/index.js:28:12
>     at Generator.next (<anonymous>)
>     at step (/Users/armenzg/repos/health/backend/build/nimbledroid.js:129:191)
>     at /Users/armenzg/repos/health/backend/build/nimbledroid.js:129:361
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> ✨  Done in 121.86s.
> armenzg@armenzg-mbp backend$ echo $?
> 0

**Comment by cpeterso** [comment]
Thanks! It's working now. The dashboard now shows the latest test results for both GeckoView and WebView, e.g. https://health.graphics/android/graph?site=https://www.reddit.com.
