### ISSUE TITLE
Fetching the release criteria spreadsheet should not require GAUTH_JSON

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-dashboard#16]
Loading http://localhost:3000/api/perf/notes returns (in the console):
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

On the server side we get the following:
```
  SyntaxError: Unexpected token u in JSON at position 0
      at JSON.parse (<anonymous>)
      at /Users/armenzg/repos/platform-health/src/perf.js:24:25
      at Generator.next (<anonymous>)
      at step (/Users/armenzg/repos/platform-health/src/perf.js:64:191)
      at /Users/armenzg/repos/platform-health/src/perf.js:64:437
      at Promise (<anonymous>)
      at /Users/armenzg/repos/platform-health/src/perf.js:64:99
      at getSpreadsheetValues (/Users/armenzg/repos/platform-health/src/perf.js:22:7)
      at /Users/armenzg/repos/platform-health/src/perf.js:144:24
      at Generator.next (<anonymous>)
      at step (/Users/armenzg/repos/platform-health/src/perf.js:64:191)
      at /Users/armenzg/repos/platform-health/src/perf.js:64:437
      at Promise (<anonymous>)
      at /Users/armenzg/repos/platform-health/src/perf.js:64:99
      at router.get.get (/Users/armenzg/repos/platform-health/src/perf.js:121:1)
      at dispatch (/Users/armenzg/repos/platform-health/node_modules/koa-compose/index.js:44:32)
```

**Comment by armenzg** [comment]
The spreadsheet is now public.
Let's make sure the code works well with it.

**Comment by armenzg** [comment]
This issue has now been moved to https://github.com/mozilla/firefox-health-backend/issues/10
which is the new backend repository.
